### ISSUE TITLE
Fatal error: Uncaught Exception: Contaos initialize.php not found

### ISSUE THREAD

**Issue by xchs** [timgatzky/pct_tabletree_widget#12]
Contao 3.5.28
pct_tabletree_widget 1.5.0

Fehlermeldung:
```
Fatal error: Uncaught Exception: Contaos initialize.php not found in: in …/system/modules/pct_tabletree_widget/assets/html/PageTableTree.php:31

Stack trace: #0 {main} thrown in …/system/modules/pct_tabletree_widget/assets/html/PageTableTree.php on line 31
```

Der Fehler lässt sich folgendermaßen reproduzieren:
* Layout > Themes > Frontend-Module > Modultyp "CustomCatalog-Liste"
* Im Abschnitt "Eigene-SQL-Einstellungen" bei "Eigene direkte Auswahl" den Button "Auswahl ändern" anklicken

Vermutlich hängt der Fehler mit den [letzten Änderungen](https://github.com/timgatzky/pct_tabletree_widget/commit/03a057ead454132c05d7a7d9a0b69265b6c414f5#diff-d3cdf43173430da85895cbb665dd247e) in Commit 03a057ead454132c05d7a7d9a0b69265b6c414f5 zusammen.

NB: Das Skript `system/initialize.php` existiert selbstverständlich. Die Contao-Installation befindet sich allerdings in einem Unterverzeichnis, d. h. der Ordner taucht auch in der URL auf und die `RewriteBase` ist auf dieses Installationsverzeichnis gesetzt.

**Comment by timgatzky** [comment]
Moin,
lokal in meinem MAMP passt das. Hast du ein Apache system?

**Comment by xchs** [comment]
Ja, die Installation läuft auf einem Apache Webserver.

**Comment by timgatzky** [comment]
Ich denke es hängt an dem Unterverzeichnis. Das ist alles mit C4 unsauber geworden durch die Symlinks und rückwärtsgerichtete Verzeichnisstruktur.

Nimm mal eine frühere Version der Datei ein. Dann wird das wieder richtig laufen. Ich werd das Unterverzeichnis-Szenario durchtesten.

**Comment by xchs** [comment]
Grad eben getestet: Mit der Vorgängerversion von `PageTableTree.php` erhalte ich keine Fehlermeldung mehr. 

Ich denke auch, dass es irgendwie an dem Unterverzeichnis liegt. Deshalb fand ich es auch sinnvoll, das oben im Ticket ausdrücklich zu erwähnen.

**Comment by timgatzky** [comment]
Magst mal den dev branch austesten?

**Comment by xchs** [comment]
Prima! Mit dem Commit aus dem Dev-Branch funktioniert es jetzt (bei mir).

**Comment by timgatzky** [comment]
Dann nehmen wir das so. Das Gro hat ohnehin keine Installationen mit Unterverzeichnissen. Danke dir.
