### ISSUE TITLE
Keine Auswahl bei Tags in tl_member

### ISSUE THREAD

**Issue by SGehle** [timgatzky/pct_tabletree_widget#35]
Ich habe einen Custom Catalog für die tl_member angelegt um diese zu erweitern. Das klappt auch problemlos. Außer wenn ich ein Tags-Attribut verwende.
Wenn ich im Frontend die entsprechenden Attribute auswähle und "Anwenden" klicke, wird im eigentlichen DIV, wo die ausgewählten Ergebnisse angezeigt werden sollten, die komplette Seite geladen - und in der Seite wird im Bereich des Custom Catalog Readers nur "tl_member" ausgegeben. 

![screen](https://user-images.githubusercontent.com/1748990/72633050-ec712f00-3957-11ea-9d56-44772671f332.PNG)

**Comment by timgatzky** [comment]
Wir befinden uns im Frontend Editing? Das klingt nach einem Ajax-Fehler. Hat die Seite Javascript-Fehler?

**Comment by SGehle** [comment]
Ja, korrekt. Frontend-Editing. Kein Fehler in der Console. Wenn die Tags die Standard-Tabelle ansprechen, entsteht das gleiche Problem, es wird wieder nur "tl_member" innerhalb des Formulars ausgegeben. In allen anderen Tabellen funktioniert das gleich Feld problemlos.

**Comment by SGehle** [comment]
Konntest du den Fehler reproduzieren? Falls nicht kann ich dir gerne ein Demo-System aufsetzen.

**Comment by SGehle** [comment]
Hier liegt das Problem: https://github.com/timgatzky/pct_customelements_plugin_cc_frontedit/blob/a7661b5d241234548799752e9ecf70813ebb2e49/system/modules/pct_customelements_plugin_cc_frontedit/PCT/CustomElements/Plugins/FrontEdit/Frontend/ModuleReader.php#L53

Wenn eine Tabelle bearbeitet werden soll, die bereits existiert, ist das Feld tableName leer, daher kann das CustomCatalogFactory Objekt nicht geladen werden.

Wenn man an dieser Stelle auch prüfen würde, ob es CustomCatalogFactory Objekt geben würde mit mode = existing und existingTable = ? funktioniert es.
Ich werde dazu morgen einen Pull-Request machen.

**Comment by timgatzky** [comment]
Ah. I see your point.
