### ISSUE TITLE
Conditions at POST-Request should be parsed with html_entity_decode

### ISSUE THREAD

**Issue by c4y** [timgatzky/pct_tabletree_widget#40]
Gebe ich beim Tags-Attribut mit eigenen Quellen eine Bedingung ein, z.B. pid=40, dann wird das = ersetzt durch &#61; und landet so in der SQL Query (also auch ohne Inserttags) und wirft damit einen Fehler. Beim Speichern der ausgewählten Attribute hängt sich das Script auf.

Im TableTreeHelper in Zeile 67 könnte man das mit 
$strConditions = $objDC->conditions = html_entity_decode(\Contao\Input::post('conditions'));
beheben.

Das Problem tritt bei mir sowohl lokal als auch bei All-Inkl auf. Allerdings hat Stephan dieses Problem lokal nicht.

**Comment by timgatzky** [comment]
Braucht es hier überhaupt das Conditions Feld und Wert? Wir befinden uns bereits im Ajax-Reload nach Auswahl der Einträge.

**Comment by c4y** [comment]
Meiner Ansicht nach nicht. Den Gedanken hatte ich auch. Stecke aber nicht so tief drin.

**Comment by timgatzky** [comment]
Ich denke das kann hier raus.
